/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uno;

import java.awt.Color;
import java.awt.Font;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Vale
 */
public final class GUIAyuda extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAyuda
     */
    public GUIAyuda() {
        initComponents();
        mostrar();
    }

    public void mostrar() {
        this.setBounds(50, 40, 550, 400);
        this.setVisible(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jTextArea1.setFont(new Font("Arial", Font.BOLD, 16));
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n     \t                     AYUDA\n\n  -> ¿Como se juega?\n\n   Para comenzar una partida, primero serán repartidas 7 cartas por jugador, y el orden de jugada será el mismo en el que se introdujeron los nombres de los jugadores.\n\n  Por turnos, se irán colocando las cartas del mismo color o del mismo tipo (a excepción de si es una carta especial negra) encima de la mesa. Si no se tiene una carta para colocar, el jugador se tendrá que cargar una carta del mazo en su turno. \n\n\n  -> ¿Cuántas cartas tiene el uno?\n\n  La baraja de cartas del uno es especial, y su número de cartas es variable. Generalmente, esta baraja está compuesta por 107 cartas, aunque hay algunas versiones que pueden traer más cartas. Además, hay dos tipos de cartas: las normales, y las especiales o de acción.\n\nLas cartas normales son solo cartas numéricas que van desde el 0 al 9.\n\nLas cartas especiales se dividen en:\n\n      - Cárgate 2: cuando se coloca esta carta, el siguiente jugador se carga dos cartas y pierde su turno. Esta carta sólo se puede poner sobre una carta del mismo color o sobre otra carta Cárgate 2. \n\n      - Reversa: esta carta cambia el sentido del juego. Al momento de que un jugador coloque la carta, el orden en el que se realizan las jugadas se invierte. Esta carta sólo se puede colocar sobre una carta del mismo color o sobre otra carta Reversa. \n\n      - Bloquea Turno: al jugador que le toque jugar pierde su turno y jugará el siguiente de acuerdo al sentido del juego. Esta carta sólo se puede colocar sobre una carta del mismo color o sobre otra carta del mismo tipo. \n\n      - Cambio de color: el jugador que coloque esta carta dirá el nuevo color que se jugará o puede repetir el que ya estaba para descartarse. \n\n      - Cárgate 4: quien tira esta carta escoge su color y hace que el siguiente jugador robe 4 cartas del mazo y pierda su turno. ");
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

}
