/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uno;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jenderlly
 */
public class GUIJugadores extends javax.swing.JFrame {

    public ArrayList<String> idJugadoresLabel;

    public GUIJugadores() {
        initComponents();
        idJugadoresLabel = new ArrayList<>();
    }

    public String[] getIds() {
        String[] ids = idJugadoresLabel.toArray(new String[idJugadoresLabel.size()]);
        return ids;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonEmpezar = new javax.swing.JButton();
        textboxJugador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jugador1 = new javax.swing.JLabel();
        jugador2 = new javax.swing.JLabel();
        jugador3 = new javax.swing.JLabel();
        jugador4 = new javax.swing.JLabel();
        jugador5 = new javax.swing.JLabel();
        jugador6 = new javax.swing.JLabel();
        jugador7 = new javax.swing.JLabel();
        jugador8 = new javax.swing.JLabel();
        jugador9 = new javax.swing.JLabel();
        jugador10 = new javax.swing.JLabel();

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel11.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonGuardar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonEmpezar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        botonEmpezar.setText("Empezar");
        botonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpezarActionPerformed(evt);
            }
        });

        textboxJugador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textboxJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxJugadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setText("Agrega los nombres de los jugadores");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("Jugadores:");

        jugador1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        jugador10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador9)
                    .addComponent(jugador10))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jugador5)
                    .addComponent(jugador6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jugador3)
                    .addComponent(jugador1))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jugador4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugador7)
                    .addComponent(jugador8))
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(botonGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEmpezar)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(textboxJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador1)
                    .addComponent(jugador2)
                    .addComponent(jugador5)
                    .addComponent(jugador9)
                    .addComponent(jugador7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugador3)
                    .addComponent(jugador4)
                    .addComponent(jugador6)
                    .addComponent(jugador8)
                    .addComponent(jugador10))
                .addGap(30, 30, 30)
                .addComponent(textboxJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonEmpezar))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if (textboxJugador.getText().isEmpty()) { //si el campo de texto no está vacio se van cargando los jugadores
            JLabel mensaje = new JLabel("Por favor inserte un nombre");
            mensaje.setFont(new Font("Arial", Font.BOLD, 48));
            JOptionPane.showMessageDialog(null, mensaje);
        } else {
            String nombre = textboxJugador.getText().trim();
            if (idJugadoresLabel.contains(nombre)) {
                JLabel mensaje = new JLabel("Este nombre ya ha sido introducido!");
                mensaje.setFont(new Font("Arial", Font.BOLD, 48));
                JOptionPane.showMessageDialog(null, mensaje);
                textboxJugador.setText("");
            } else {
                idJugadoresLabel.add(nombre);
                switch (idJugadoresLabel.size()) {
                    case 1:
                        jugador1.setText(idJugadoresLabel.get(0));
                        break;
                    case 2:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        break;
                    case 3:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        break;
                    case 4:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        jugador4.setText(idJugadoresLabel.get(3));
                        break;
                    case 5:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        break;
                    case 6:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        jugador6.setText(idJugadoresLabel.get(5));
                        break;
                    case 7:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        jugador6.setText(idJugadoresLabel.get(5));
                        jugador7.setText(idJugadoresLabel.get(6));
                        break;
                    case 8:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador3.setText(idJugadoresLabel.get(2));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        jugador6.setText(idJugadoresLabel.get(5));
                        jugador7.setText(idJugadoresLabel.get(6));
                        jugador8.setText(idJugadoresLabel.get(7));
                        break;
                    case 9:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        jugador6.setText(idJugadoresLabel.get(5));
                        jugador7.setText(idJugadoresLabel.get(6));
                        jugador8.setText(idJugadoresLabel.get(7));
                        jugador9.setText(idJugadoresLabel.get(8));
                        break;
                    case 10:
                        jugador1.setText(idJugadoresLabel.get(0));
                        jugador2.setText(idJugadoresLabel.get(1));
                        jugador4.setText(idJugadoresLabel.get(3));
                        jugador5.setText(idJugadoresLabel.get(4));
                        jugador6.setText(idJugadoresLabel.get(5));
                        jugador7.setText(idJugadoresLabel.get(6));
                        jugador8.setText(idJugadoresLabel.get(7));
                        jugador9.setText(idJugadoresLabel.get(8));
                        jugador10.setText(idJugadoresLabel.get(9));
                        break;
                    default:
                        break;
                }

                if (!idJugadoresLabel.isEmpty() && idJugadoresLabel.size() < 11) {
                    JLabel mensaje = new JLabel("Se ha guardado al jugador!");
                    mensaje.setFont(new Font("Arial", Font.BOLD, 48));
                    JOptionPane.showMessageDialog(null, mensaje);
                    textboxJugador.setText("");
                }
                if (idJugadoresLabel.size() == 11) { //no pueden cargarse mas de 10
                    idJugadoresLabel.remove(nombre);
                    JLabel mensaje = new JLabel("Se han guardado el maximo de jugadores posibles(10)!");
                    mensaje.setFont(new Font("Arial", Font.BOLD, 48));
                    JOptionPane.showMessageDialog(null, mensaje);
                    textboxJugador.setText("");
                }

            }

        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpezarActionPerformed
        if (idJugadoresLabel.size() == 1 || idJugadoresLabel.size() == 0) {
            JLabel mensaje = new JLabel("Se requiere almenos 2 jugadores para jugar!");
            mensaje.setFont(new Font("Arial", Font.BOLD, 48));
            JOptionPane.showMessageDialog(null, mensaje);
            textboxJugador.setText("");
        } else {
            this.dispose();
            new GUIJuego(idJugadoresLabel, true).setVisible(true);
        }
    }//GEN-LAST:event_botonEmpezarActionPerformed

    private void textboxJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEmpezar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jugador1;
    private javax.swing.JLabel jugador10;
    private javax.swing.JLabel jugador2;
    private javax.swing.JLabel jugador3;
    private javax.swing.JLabel jugador4;
    private javax.swing.JLabel jugador5;
    private javax.swing.JLabel jugador6;
    private javax.swing.JLabel jugador7;
    private javax.swing.JLabel jugador8;
    private javax.swing.JLabel jugador9;
    private javax.swing.JTextField textboxJugador;
    // End of variables declaration//GEN-END:variables
}
