/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uno;

import java.awt.Font;
import static java.awt.SystemColor.window;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.stream.Collectors;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jenderlly
 */
public class GUIJuego extends javax.swing.JFrame {

    private GUIJugadores jugadores = new GUIJugadores();
    ArrayList<String> tempo = new ArrayList<>();
    String[] ids;
    Juego juego;
    ArrayList<JButton> botonesCartas = new ArrayList<JButton>();
    ArrayList<String> idCartas;
    VentanaEmergente ventana;

    public GUIJuego() {

    }

    public GUIJuego(ArrayList<String> idJugadores,boolean jn) {
        initComponents();
        tempo = idJugadores;
        ids = tempo.toArray(new String[tempo.size()]);
        juego = new Juego(ids);
        llenarLista();
        juego.start(juego,jn);
        setId();
        botonCartaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/Imagenes2/" + juego.getCartaActual().toString() + ".png")));//asigna la imagen de la carta con la que se empieza
        setIconoBoton();
    }

    public void setIconoBoton() { //este método asigna los iconos de sus respectivas cartas a los botones 
        String mano = juego.getManoJugador(juego.getJugadorActual()).stream().map(Object::toString).collect(Collectors.joining(","));
        String[] pngNombres = mano.split(",");
        idCartas = new ArrayList<>(Arrays.asList(pngNombres));
        for (int i = 0; i < idCartas.size(); i++) {
            botonesCartas.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/Imagenes2/" + idCartas.get(i) + ".png")));
        }
        for (int i = idCartas.size(); i < botonesCartas.size(); i++) {
            botonesCartas.get(i).setIcon(null);
        }
    }

    public void llenarLista() { //llena los botones a la lista
        botonesCartas.add(botonCarta1);
        botonesCartas.add(botonCarta2);
        botonesCartas.add(botonCarta3);
        botonesCartas.add(botonCarta4);
        botonesCartas.add(botonCarta5);
        botonesCartas.add(botonCarta6);
        botonesCartas.add(botonCarta7);
        botonesCartas.add(botonCarta8);
        botonesCartas.add(botonCarta9);
        botonesCartas.add(botonCarta10);
        botonesCartas.add(botonCarta11);
        botonesCartas.add(botonCarta12);
        botonesCartas.add(botonCarta13);
        botonesCartas.add(botonCarta14);
        botonesCartas.add(botonCarta15);
        botonesCartas.add(botonCarta16);
        botonesCartas.add(botonCarta17);
        botonesCartas.add(botonCarta18);
        botonesCartas.add(botonCarta19);
        botonesCartas.add(botonCarta20);
        botonesCartas.add(botonCarta21);
        botonesCartas.add(botonCarta22);
        botonesCartas.add(botonCarta23);
        botonesCartas.add(botonCarta24);
        botonesCartas.add(botonCarta25);
        botonesCartas.add(botonCarta26);
    }

    public void setId(String jugadorActual) { //aquí se muestra el jugador actual en pantalla
        idJugadorLabel.setText("Turno de " + jugadorActual);
    }

    public void setId() { //
        String jugadorActual = juego.getJugadorActual();
        idJugadorLabel.setText("Turno de " + jugadorActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCarta1 = new javax.swing.JButton();
        botonCarta2 = new javax.swing.JButton();
        botonCarta3 = new javax.swing.JButton();
        botonCarta4 = new javax.swing.JButton();
        botonCarta5 = new javax.swing.JButton();
        botonCarta6 = new javax.swing.JButton();
        botonCarta7 = new javax.swing.JButton();
        botonCarta8 = new javax.swing.JButton();
        botonCarta9 = new javax.swing.JButton();
        botonCarta10 = new javax.swing.JButton();
        botonCarta11 = new javax.swing.JButton();
        botonCarta12 = new javax.swing.JButton();
        botonCarta13 = new javax.swing.JButton();
        botonCarta14 = new javax.swing.JButton();
        botonCarta15 = new javax.swing.JButton();
        botonCarta16 = new javax.swing.JButton();
        botonCarta17 = new javax.swing.JButton();
        botonCarta18 = new javax.swing.JButton();
        botonCarta19 = new javax.swing.JButton();
        botonCarta20 = new javax.swing.JButton();
        botonCarta21 = new javax.swing.JButton();
        botonCarta22 = new javax.swing.JButton();
        botonCarta23 = new javax.swing.JButton();
        botonCarta24 = new javax.swing.JButton();
        botonCarta25 = new javax.swing.JButton();
        botonCarta26 = new javax.swing.JButton();
        botonCargarseCarta = new javax.swing.JButton();
        botonCartaActual = new javax.swing.JButton();
        botonCartaMazo = new javax.swing.JButton();
        idJugadorLabel = new javax.swing.JLabel();
        botonSaltarTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNO");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));

        botonCarta1.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta1ActionPerformed(evt);
            }
        });

        botonCarta2.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta2ActionPerformed(evt);
            }
        });

        botonCarta3.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta3ActionPerformed(evt);
            }
        });

        botonCarta4.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta4ActionPerformed(evt);
            }
        });

        botonCarta5.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta5ActionPerformed(evt);
            }
        });

        botonCarta6.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta6ActionPerformed(evt);
            }
        });

        botonCarta7.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta7ActionPerformed(evt);
            }
        });

        botonCarta8.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta8ActionPerformed(evt);
            }
        });

        botonCarta9.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta9ActionPerformed(evt);
            }
        });

        botonCarta10.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta10ActionPerformed(evt);
            }
        });

        botonCarta11.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta11ActionPerformed(evt);
            }
        });

        botonCarta12.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta12ActionPerformed(evt);
            }
        });

        botonCarta13.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta13ActionPerformed(evt);
            }
        });

        botonCarta14.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta14ActionPerformed(evt);
            }
        });

        botonCarta15.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta15ActionPerformed(evt);
            }
        });

        botonCarta16.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta16ActionPerformed(evt);
            }
        });

        botonCarta17.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta17ActionPerformed(evt);
            }
        });

        botonCarta18.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta18ActionPerformed(evt);
            }
        });

        botonCarta19.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta19ActionPerformed(evt);
            }
        });

        botonCarta20.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta20ActionPerformed(evt);
            }
        });

        botonCarta21.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta21ActionPerformed(evt);
            }
        });

        botonCarta22.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta22ActionPerformed(evt);
            }
        });

        botonCarta23.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta23ActionPerformed(evt);
            }
        });

        botonCarta24.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta24ActionPerformed(evt);
            }
        });

        botonCarta25.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta25ActionPerformed(evt);
            }
        });

        botonCarta26.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCarta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCarta26ActionPerformed(evt);
            }
        });

        botonCargarseCarta.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonCargarseCarta.setText("Cargarse carta");
        botonCargarseCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarseCartaActionPerformed(evt);
            }
        });

        botonCartaActual.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCartaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaActualActionPerformed(evt);
            }
        });

        botonCartaMazo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uno/Imagenes/uno.png"))); // NOI18N
        botonCartaMazo.setPreferredSize(new java.awt.Dimension(86, 129));
        botonCartaMazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCartaMazoActionPerformed(evt);
            }
        });

        idJugadorLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        idJugadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonSaltarTurno.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        botonSaltarTurno.setText("Saltar turno");
        botonSaltarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSaltarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonCargarseCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSaltarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(idJugadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(504, 504, 504))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(544, 544, 544)
                        .addComponent(botonCartaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonCartaMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonCarta26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCartaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCartaMazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCargarseCarta)
                    .addComponent(botonSaltarTurno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(idJugadorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCarta14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCarta13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCarta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCarta24ActionPerformed

    
    //cada boton le toca su respectiva carta dentro de la lista de la mono de cada jugador
    private void botonCarta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta23ActionPerformed
        if (idCartas.get(22) != null) { //si hay una carta en esta posición te sale una ventana emergente para poder elegir si jugarla o no
            int i = 22;
            String idCarta = idCartas.get(22);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta23ActionPerformed

    private void botonCarta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta22ActionPerformed
        if (idCartas.get(21) != null) {
            int i = 21;
            String idCarta = idCartas.get(21);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta22ActionPerformed

    private void botonCarta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta21ActionPerformed
        if (idCartas.get(20) != null) {
            int i = 20;
            String idCarta = idCartas.get(20);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta21ActionPerformed

    private void botonCarta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta20ActionPerformed
        if (idCartas.get(19) != null) {
            int i = 19;
            String idCarta = idCartas.get(19);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta20ActionPerformed

    private void botonCarta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta19ActionPerformed
        if (idCartas.get(18) != null) {
            int i = 18;
            String idCarta = idCartas.get(18);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta19ActionPerformed

    private void botonCarta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta18ActionPerformed
        if (idCartas.get(17) != null) {
            int i = 17;
            String idCarta = idCartas.get(17);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta18ActionPerformed

    private void botonCarta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta17ActionPerformed
        if (idCartas.get(16) != null) {
            int i = 16;
            String idCarta = idCartas.get(16);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta17ActionPerformed

    private void botonCarta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta13ActionPerformed
        if (idCartas.get(12) != null) {
            int i = 12;
            String idCarta = idCartas.get(12);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta13ActionPerformed

    private void botonCarta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta12ActionPerformed
        if (idCartas.get(11) != null) {
            int i = 11;
            String idCarta = idCartas.get(11);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta12ActionPerformed

    private void botonCarta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta11ActionPerformed
        if (idCartas.get(10) != null) {
            int i = 10;
            String idCarta = idCartas.get(10);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta11ActionPerformed

    private void botonCarta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta10ActionPerformed
        if (idCartas.get(9) != null) {
            int i = 9;
            String idCarta = idCartas.get(9);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta10ActionPerformed

    private void botonCarta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta9ActionPerformed
        if (idCartas.get(8) != null) {
            int i = 8;
            String idCarta = idCartas.get(8);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta9ActionPerformed

    private void botonCartaMazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaMazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCartaMazoActionPerformed

    private void botonCarta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta8ActionPerformed
        if (idCartas.get(7) != null) {
            int i = 7;
            String idCarta = idCartas.get(7);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta8ActionPerformed

    private void botonCarta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta7ActionPerformed
        if (idCartas.get(6) != null) {
            int i = 6;
            String idCarta = idCartas.get(6);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta7ActionPerformed

    //botón cargarse carta
    private void botonCargarseCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarseCartaActionPerformed

        if (juego.getCarga() == false) { //comprueba que este jugador no se haya ya cargado una carta en este turno
            try {
                juego.sacarCarta2(juego.getJugadorActual());
                juego.setCarga(true);
            } catch (InvalidColorException | InvalidNumeroException | InvalidTurnoException e) {
                Logger.getLogger(GUIJuego.class.getName()).log(Level.SEVERE, null, e);
            }
        } else { //si intentas cargarte mas de una carta te salta tu turno
            JLabel mensaje = new JLabel(juego.getJugadorActual() + " ya se cargó una carta!");
            mensaje.setFont(new Font("Arial", Font.BOLD, 48));
            JOptionPane.showMessageDialog(null, mensaje);
            juego.turno();
        }

        this.setId(juego.getJugadorActual());
        this.setIconoBoton();

    }//GEN-LAST:event_botonCargarseCartaActionPerformed

    private void botonCarta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta6ActionPerformed
        if (idCartas.get(5) != null) {
            int i = 5;
            String idCarta = idCartas.get(5);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta6ActionPerformed

    private void botonCarta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta5ActionPerformed
        if (idCartas.get(4) != null) {
            int i = 4;
            String idCarta = idCartas.get(4);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta5ActionPerformed

    private void botonCarta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCarta26ActionPerformed

    private void botonCarta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta4ActionPerformed
        if (idCartas.get(3) != null) {
            int i = 3;
            String idCarta = idCartas.get(3);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta4ActionPerformed

    private void botonCarta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCarta25ActionPerformed

    private void botonCartaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCartaActualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCartaActualActionPerformed

    private void botonCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta1ActionPerformed
        if (idCartas.get(0) != null) {
            int i = 0;
            String idCarta = idCartas.get(0);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta1ActionPerformed

    private void botonCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta2ActionPerformed
        if (idCartas.get(1) != null) {
            int i = 1;
            String idCarta = idCartas.get(1);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta2ActionPerformed

    private void botonCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta3ActionPerformed
        if (idCartas.get(2) != null) {
            int i = 2;
            String idCarta = idCartas.get(2);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta3ActionPerformed

    private void botonCarta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta14ActionPerformed
        if (idCartas.get(13) != null) {
            int i = 13;
            String idCarta = idCartas.get(13);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta14ActionPerformed

    private void botonCarta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta15ActionPerformed
        if (idCartas.get(14) != null) {
            int i = 14;
            String idCarta = idCartas.get(14);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta15ActionPerformed

    private void botonCarta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCarta16ActionPerformed
        if (idCartas.get(15) != null) {
            int i = 15;
            String idCarta = idCartas.get(15);
            ventana = new VentanaEmergente(idCarta, juego, i, botonesCartas, this, botonCartaActual);
            ventana.setBounds(500, 40, 400, 500);
            ventana.setVisible(true);
            ventana.setResizable(false);
            ventana.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        }
    }//GEN-LAST:event_botonCarta16ActionPerformed

    //botón saltar turno
    private void botonSaltarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSaltarTurnoActionPerformed
        JLabel mensaje = new JLabel(juego.getJugadorActual() + " se saltó el turno!");
        mensaje.setFont(new Font("Arial", Font.BOLD, 48));
        JOptionPane.showMessageDialog(null, mensaje);
        juego.turno();
        this.setId(juego.getJugadorActual());
        this.setIconoBoton();

    }//GEN-LAST:event_botonSaltarTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJuego.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarseCarta;
    private javax.swing.JButton botonCarta1;
    private javax.swing.JButton botonCarta10;
    private javax.swing.JButton botonCarta11;
    private javax.swing.JButton botonCarta12;
    private javax.swing.JButton botonCarta13;
    private javax.swing.JButton botonCarta14;
    private javax.swing.JButton botonCarta15;
    private javax.swing.JButton botonCarta16;
    private javax.swing.JButton botonCarta17;
    private javax.swing.JButton botonCarta18;
    private javax.swing.JButton botonCarta19;
    private javax.swing.JButton botonCarta2;
    private javax.swing.JButton botonCarta20;
    private javax.swing.JButton botonCarta21;
    private javax.swing.JButton botonCarta22;
    private javax.swing.JButton botonCarta23;
    private javax.swing.JButton botonCarta24;
    private javax.swing.JButton botonCarta25;
    private javax.swing.JButton botonCarta26;
    private javax.swing.JButton botonCarta3;
    private javax.swing.JButton botonCarta4;
    private javax.swing.JButton botonCarta5;
    private javax.swing.JButton botonCarta6;
    private javax.swing.JButton botonCarta7;
    private javax.swing.JButton botonCarta8;
    private javax.swing.JButton botonCarta9;
    private javax.swing.JButton botonCartaActual;
    private javax.swing.JButton botonCartaMazo;
    private javax.swing.JButton botonSaltarTurno;
    private javax.swing.JLabel idJugadorLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
